format = """

$directory $fill $git_branch$git_status$git_metrics        

[](fg:Black)\
[](fg:Blue bg:Black)\
[](fg:Green bg:Blue)\
[   ](bg:Green fg:Black)\
[ ](fg:Green)\
"""

continuation_prompt = "[   ](fg:Green)"

# symbols: https://www.nerdfonts.com/cheat-sheet

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[fill]
symbol = ' '
[username]
show_always = true
style_user = "bg:Purple fg:White"
style_root = "bg:Purple fg:White"
format = """\
[ ](Purple)\
[ Z☻llinger ]($style)\
[](fg:Purple)\
"""

[directory]
style = "bg:Blue fg:Black"
format = """\
[](fg:blue)\
[ $path ]($style)\
[](fg:blue)\
"""
truncation_length = 3 
truncation_symbol = "♪~ ᕕ(ᐛ)ᕗ/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh
[directory.substitutions]
style = "bg:Blue fg:White"
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = "ಠ⌣ಠ"
"github.houston.softwaregrp.net" = "⩄"

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
style = "bg:green fg:black"
symbol = ""
format = """\
[](fg:green)\
[ $symbol '$branch']($style)\
[](fg:green bg:black)\
"""

[git_status]
style = "bg:Black fg:green"
up_to_date = '👍'
format = """\
[ $all_status$ahead_behind]($style)\
[](fg:Black)\
"""
